cmd: vagrant ssh -- "cd teaching; ./build_current_file {PROJECT_PATH} {FILE_ACTIVE}"
name: current
targets:
  handouts:
    cmd: vagrant ssh -- "cd teaching; make handouts"
  all:
    cmd: vagrant ssh -- "cd teaching; make all"
  init:
    cmd: vagrant up
