cmd: docker-compose run --entrypoint ./bin/build_current_file make {PROJECT_PATH} {FILE_ACTIVE}
name: current
targets:
  handouts:
    cmd: docker-compose run make handouts
  all:
    cmd: docker-compose run make all
  update_docker_image:
    cmd: docker-compose pull
