cmd: vagrant ssh -- "./bin/build_current_file {PROJECT_PATH} {FILE_ACTIVE}"
name: current
targets:
  handouts:
    cmd: vagrant ssh -- "docker-compose run make handouts"
  all:
    cmd: vagrant ssh -- "docker-compose run make all"
  init:
    cmd: vagrant up
  vagrant:
    cmd: vagrant halt && vagrant provision && vagrant up
