cmd: docker run -v {PROJECT_PATH}:/teaching:delegated --entrypoint './bin/build_current_file' bknguyen/teaching {PROJECT_PATH} {FILE_ACTIVE}
name: current
targets:
  handouts:
    cmd: docker run -v {PROJECT_PATH}:/teaching:delegated bknguyen/teaching handouts
  all:
    cmd: docker run -v {PROJECT_PATH}:/teaching:delegated bknguyen/teaching all
  clean:
    cmd: docker run -v {PROJECT_PATH}:/teaching:delegated bknguyen/teaching clean
  update_docker:
    cmd: docker pull bknguyen/teaching
