cmd: vagrant ssh -c 'cd /vagrant; ./bin/build_current_file {FILE_ACTIVE_NAME}'
name: current
targets:
  handouts:
    cmd: vagrant ssh -c 'cd /vagrant; make -j 10 handouts'
  all:
    cmd: vagrant ssh -c 'cd /vagrant; make -j 10 all'
  clean:
    cmd: vagrant ssh -c 'cd /vagrant; make -j 10 clean'
  start_vm:
    cmd: vagrant up
  stop_vm:
    cmd: vagrant halt -f
  update_software_vm:
    cmd: vagrant provision
  reset_vm:
    cmd: vagrant halt -f && vagrant up --provision
  nfs_for_windows:
    cmd: vagrant halt -f && vagrant plugin install vagrant-winnfsd && vagrant up
