cmd: vagrant ssh -- "./bin/build_current_file {FILE_ACTIVE_NAME}"
name: current
targets:
  handouts:
    cmd: vagrant ssh -- "make handouts"
  all:
    cmd: vagrant ssh -- "make all"
  clean:
    cmd: vagrant ssh -- "make clean"
  start_vm:
    cmd: vagrant up
  stop_vm:
    cmd: vagrant halt -f
  update_software_vm:
    cmd: vagrant provision
  reset_vm:
    cmd: vagrant halt -f && vagrant provision && vagrant up
