version: '3.1'
services:
  make:
    image: bknguyen/teaching:latest
    build: .
    user: ${ID}
    ports:
      - "1234:1234"
      - "5000:5000"
    volumes:
      - .:/teaching:delegated
  manim:
    image: eulertour/manim:latest
    entrypoint:
      - ./manim.py
    user: ${ID}
    volumes:
      - ./videos:/videos
    working_dir: /videos
    network_mode: "none"
