version: '3.1'
services:
  make:
    image: bknguyen/teaching:latest
    build: .
    user: ${ID}
    volumes:
      - .:/teaching:delegated
  manim:
    image: eulertour/manim:latest
    entrypoint:
      - ./manim.py
    user: ${ID}
    volumes:
      - ./videos:/videos
    working_dir: /videos
    network_mode: "none"
