environments = {
    "Code": {
        "title": "Code",
        "prefix": "\\faCode",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Definition": {
        "title": "Definition",
        "prefix": "\\faStar \\faBook",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Exercise": {
        "title": "Exercise",
        "prefix": "\\faBook \\faPencil",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Example": {
        "title": "Example",
        "prefix": "\\faPencilSquare",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Extension": {
        "title": "Extension",
        "prefix": "\\faPlus",
        "tcolor": "darkgreen",
        "bgcolor": "lightgreen",
    },
    "Formula": {
        "title": "Formula",
        "prefix": "\\faSuperscript",
        "tcolor": "darkorange",
        "bgcolor": "lightorange",
    },
    "Hint": {
        "title": "Hint",
        "prefix": "\\faLightbulbO",
        "tcolor": "darkgreen",
        "bgcolor": "lightgreen",
    },
    "Idea": {
        "title": "Key Idea",
        "prefix": "\\faLightbulbO",
        "tcolor": "darkgreen",
        "bgcolor": "lightgreen",
    },
    "Method": {
        "title": "Method",
        "prefix": "\\faList \\faGears",
        "tcolor": "darkgray",
        "bgcolor": "verylightgray",
    },
    "Objective": {
        "title": "Lesson Objective",
        "prefix": "\\faList\\ \\faPencilSquare",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Question": {
        "title": "Question",
        "prefix": "\\faQuestionCircle",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Quote": {
        "title": "Quote",
        "prefix": "\\faQuoteLeft",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Recall": {
        "title": "Recall",
        "prefix": "\\faHistory",
        "tcolor": "darkorange",
        "bgcolor": "lightorange",
    },
    "Remark": {
        "title": "Remark",
        "prefix": "\\faPencil",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Remember": {
        "title": "Remember",
        "prefix": "\\faDownload",
        "tcolor": "darkorange",
        "bgcolor": "lightorange",
    },
    "Result": {
        "title": "Result",
        "prefix": "\\faImage",
        "tcolor": "darkgreen",
        "bgcolor": "lightgreen",
    },
    "Solution": {
        "title": "Solution",
        "prefix": "\\faPencilSquareO \\faCheck",
        "tcolor": "darkgreen",
        "bgcolor": "lightgreen",
    },
    "Starter": {
        "title": "Starter",
        "prefix": "\\faBook \\faPencil \\faClockO",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Theorem": {
        "title": "Theorem",
        "prefix": "\\faBook\ \\faStar",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Vocabulary": {
        "title": "Vocabulary",
        "prefix": "\\faLanguage",
        "tcolor": "darkblue",
        "bgcolor": "lightblue",
    },
    "Warning": {
        "title": "Warning",
        "prefix": "\\faWarning",
        "tcolor": "darkred",
        "bgcolor": "lightred",
    },
}
