name: Create PDFS

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://bknguyen/teaching:latest
        with:
          args: "deploy"
      - uses: actions/upload-artifact@master
        with:
          name: www
          path: www
