name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://bknguyen/teaching:latest
        with:
          args: "handouts"
      - run: rsync -am --include '*/' --include '*.pdf' --exclude '*' . pdfs
      - uses: actions/upload-artifact@master
        with:
          name: pdfs
          path: pdfs
